import createClient from 'openapi-fetch';

import type { paths } from './schema';

// generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: 'https://api-giraffy.gosyav.com/',
});
