/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/notifications/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get New Users Notifications */
    get: operations['get_new_users_notifications_notifications__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Отримання коктретного оголошення за id
     * @description Ендпоінт для отримання конкретного оголошення. Приймає id повертає саме оголошення
     */
    get: operations['get_product_by_id_products__product_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Фільтрований список продуктів */
    get: operations['get_products_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/faq': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Faq Get */
    get: operations['faq_get_faq_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Отримання коментарів до продукта */
    get: operations['get_comments_by_product_comments_products__product_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/comments/{comment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Видалення коментаря до продукта */
    delete: operations['delete_comment_comments__comment_id__delete'];
    options?: never;
    head?: never;
    /** Апдейт коментаря до товару */
    patch: operations['update_comment_comments__comment_id__patch'];
    trace?: never;
  };
  '/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Створення нового коментаря
     * @description Ендпоінт для створення нового коментаря, доступний лише авторизованим користувачам.
     */
    post: operations['create_comment_comments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/wishlists': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Отримання списку всіх продуктів з вішліста юзера
     * @description Віддає список продуктів доданних до вішліста авторизованного юзера
     */
    get: operations['get_user_wishlist_wishlists_get'];
    put?: never;
    /**
     * Додавання продукту до вішліста
     * @description Ендпоінт для додавання продутку до списку бажанного. Приймає product_id
     */
    post: operations['add_to_wishlist_wishlists_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/wishlists/remove/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Видалення продукту з вішліста
     * @description Ендпоінт для видалення продукту з вішліста за product_id
     */
    delete: operations['remove_from_wishlist_wishlists_remove__product_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Auth:Db.Login */
    post: operations['auth_db_login_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Auth:Db.Logout */
    post: operations['auth_db_logout_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Реєстрація користувача
     * @description Ендпоінт для створення нового користувача. Обов'язковими є email, password, phone_number
     */
    post: operations['register_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/user_login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Логін користувача
     * @description Ендпоінт для логіну користувача. Приймає в себе json з імейлом та паролем. Повертає access_token
     */
    post: operations['login_auth_user_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/user_logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Логаут для користувача
     * @description Екдпоінт для виходу з системи користувача. Видаляє аксесс токен з бд
     */
    post: operations['logout_auth_user_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Рефреш токен
     * @description Ендпоінт для оновлення access_token по refresh_token
     */
    post: operations['refresh_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Запит на скидання паролю
     * @description Введіть емейл, щоб отримати лист з токеном
     */
    post: operations['forgot_password_auth_request_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Зміна паролю за токеном
     * @description Введіть отриманий токен з листа та новий пароль
     */
    post: operations['reset_users_password_auth_confirm_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Users:Current User */
    get: operations['users_current_user_users_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Users:Patch Current User */
    patch: operations['users_patch_current_user_users_me_patch'];
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Users:User */
    get: operations['users_user_users__id__get'];
    put?: never;
    post?: never;
    /** Users:Delete User */
    delete: operations['users_delete_user_users__id__delete'];
    options?: never;
    head?: never;
    /** Users:Patch User */
    patch: operations['users_patch_user_users__id__patch'];
    trace?: never;
  };
  '/auth/google/authorize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Oauth:Google.Db.Authorize */
    get: operations['oauth_google_db_authorize_auth_google_authorize_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Oauth:Google.Db.Callback
     * @description The response varies based on the authentication backend used.
     */
    get: operations['oauth_google_db_callback_auth_google_callback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{user_id}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Отримання відгуків продавця */
    get: operations['get_reviews_users__user_id__reviews_get'];
    put?: never;
    /**
     * Виставлення рейтинга продавцю
     * @description Ендпоінт для виставлення рейтинга продавцю, доступний лише авторизованим користувачам.
     */
    post: operations['create_review_users__user_id__reviews_post'];
    /** Видалення відгука на продавця */
    delete: operations['delete_review_users__user_id__reviews_delete'];
    options?: never;
    head?: never;
    /** Апдейт відгука на продавця */
    patch: operations['update_review_users__user_id__reviews_patch'];
    trace?: never;
  };
  '/users/{user_id}/rating': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Отримання фінального рейтинга продавця */
    get: operations['get_rating_users__user_id__rating_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All
     * @description Отримання списка всіх категорій
     */
    get: operations['get_all_categories_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get One
     * @description Отримання категорії разом з потомками
     */
    get: operations['get_one_categories__category_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify_code': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Веріфікація емейлу за допомогою коду
     * @description Необхідно ввести код щоб підтвердити пошту
     */
    post: operations['verify_code_auth_verify_code_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/support/tickets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Створення заявки у службу підтримки
     * @description Ендпоінт для створення нового тікету до служби підтримки. Приймає в себе title та description. Якщо користувач не авторизованний потрібен ще user_email
     */
    post: operations['send_support_message_support_tickets_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/avatar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Завантаження аватару
     * @description Завантажте аватар, обмеження до 5мб, тип файлу .jpg, .png, .webp,відповідь має бути посилання фото в хмарі
     */
    post: operations['upload_avatar_user_avatar_post'];
    /**
     * Видалення аватару
     * @description Фото аватару видаляється, і в хмарі, і в базі даних
     */
    delete: operations['delete_avatar_user_avatar_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Отримати інформацію про поточного користувача
     * @description Отримати детальну інформацію про поточного автентифікованого користувача
     */
    get: operations['get_me_user_profile_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Видалення юзера */
    delete: operations['delete_user_users__user_id__delete'];
    options?: never;
    head?: never;
    /** Часткова зміна даних юзера */
    patch: operations['update_user_users__user_id__patch'];
    trace?: never;
  };
  '/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Фільтрований список користувачів */
    get: operations['get_users_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tickets/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Отримання списку всіх заявок у службу підтримки
     * @description Отримання всіх тікетів з можливісттю фільтруванння за статусом та пагінацією. Доступ тільки для юзерів з правами superuser
     */
    get: operations['get_support_tickets_tickets__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tickets/{ticket_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Оновлення статусу заявки у службі підтримки
     * @description Оновленнння статусу тікета за його id. Доступнні значенння: open | in_progress | resolved | closed. Доступ тільки для юзерів з правами superuser
     */
    patch: operations['update_ticket_status_tickets__ticket_id__status_patch'];
    trace?: never;
  };
  '/admin/tickets/{ticket_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Отримання детальної інформації про заявку у службі підтримки
     * @description Видає детальну інформацію про тікет за його id. Доступ тільки для юзерів з правами superuser
     */
    get: operations['get_ticket_details_tickets__ticket_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tickets{ticket_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Видалення заявки у службі підтримки
     * @description Видаляє тікет за id. Доступ тільки для юзерів з правами superuser
     */
    delete: operations['delete_ticket_tickets_ticket_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products/{product_id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Апрув товара */
    patch: operations['approve_product_products__product_id__approve_patch'];
    trace?: never;
  };
  '/admin/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Видалення продукта */
    delete: operations['delete_product_products__product_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Фільтрований список продуктів */
    get: operations['get_products_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Видалення категорії */
    delete: operations['delete_category_categories__category_id__delete'];
    options?: never;
    head?: never;
    /** Редагування категорії */
    patch: operations['update_category_categories__category_id__patch'];
    trace?: never;
  };
  '/admin/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Створення нової категорії */
    post: operations['create_category_categories_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profiles/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Фільтрований список продуктів */
    get: operations['get_products_get'];
    put?: never;
    /**
     * Створення нового оголошення
     * @description Ендпоінт для створення нового оголошення, доступний лише авторизованим користувачам. Обов'язковими є всі поля окрім category_id або category, з них можна передавати один параметр. Приймає дані оголошення у форматі JSON та повертає повідомлення про успішнне створення оголошення
     */
    post: operations['create_product_products_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profiles/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Отримання коктретного оголошення за id
     * @description Ендпоінт для отримання конкретного оголошення. Приймає id повертає саме оголошення
     */
    get: operations['get_product_by_id_products__product_id__get'];
    put?: never;
    post?: never;
    /** Видалення продукта */
    delete: operations['delete_product_products__product_id__delete'];
    options?: never;
    head?: never;
    /** Апдейт товара */
    patch: operations['update_product_products__product_id__patch'];
    trace?: never;
  };
  '/authenticated-route': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Authenticated Route */
    get: operations['authenticated_route_authenticated_route_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/button': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Button */
    get: operations['button_button_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssignedAdminOut */
    AssignedAdminOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
    };
    /** BearerResponse */
    BearerResponse: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** Body_auth_db_login_auth_login_post */
    Body_auth_db_login_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_upload_avatar_user_avatar_post */
    Body_upload_avatar_user_avatar_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** CategoryRead */
    CategoryRead: {
      /** Category Id */
      category_id: number;
      /** Name */
      name: string;
      /** Image Url */
      image_url?: string | null;
      /** Parent Category Id */
      parent_category_id?: number | null;
      /**
       * Is Deleted
       * @default false
       */
      is_deleted: boolean;
      /** Deleted At */
      deleted_at?: string | null;
      /**
       * Children
       * @default []
       */
      children: components['schemas']['CategoryRead'][];
    };
    /** CommentCreate */
    CommentCreate: {
      /** Product Id */
      product_id: number;
      /** Parent Comment Id */
      parent_comment_id?: number | null;
      /** Text */
      text: string;
    };
    /** CommentRead */
    CommentRead: {
      /** Comment Id */
      comment_id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Product Id */
      product_id: number;
      /** Parent Comment Id */
      parent_comment_id?: number | null;
      /** Text */
      text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
      /**
       * Children
       * @default []
       */
      children: components['schemas']['CommentRead'][];
      user: components['schemas']['UserReadSimple'];
    };
    /** CommentUpdate */
    CommentUpdate: {
      /** Text */
      text: string;
    };
    /**
     * ConfirmResetPasswordResponse
     * @example {
     *       "message": "Пароль успішно змінено"
     *     }
     */
    ConfirmResetPasswordResponse: {
      /** Message */
      message: string;
    };
    /** CreateSupportTicket */
    CreateSupportTicket: {
      /**
       * User Email
       * @description Email користувача, який створює заявку, якщо не авторизований
       */
      user_email?: string | null;
      /** Title */
      title: string;
      /** Description */
      description: string;
    };
    /** ErrorModel */
    ErrorModel: {
      /** Detail */
      detail:
        | string
        | {
            [key: string]: string;
          };
    };
    /** FAQResponse */
    FAQResponse: {
      /** Faq Id */
      faq_id: number;
      /** Question */
      question: string;
      /** Answer */
      answer: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LogoutBody */
    LogoutBody: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** Notifications */
    Notifications: {
      /** Id */
      id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Text */
      text: string;
      /**
       * Datetime
       * Format: date
       */
      datetime: string;
      /**
       * Is Read
       * @default false
       */
      is_read: boolean;
    };
    /** OAuth2AuthorizeResponse */
    OAuth2AuthorizeResponse: {
      /** Authorization Url */
      authorization_url: string;
    };
    /** Page[CommentRead] */
    Page_CommentRead_: {
      /** Items */
      items: components['schemas']['CommentRead'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Pages */
      pages: number;
    };
    /** ProductImageRead */
    ProductImageRead: {
      /** Image Id */
      image_id: number;
      /** Product Id */
      product_id: number;
      /** Image Url */
      image_url: string;
    };
    /** ProductRead */
    ProductRead: {
      /** Product Id */
      product_id: number;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Price */
      price: number;
      /** Category Id */
      category_id: number;
      /** Location */
      location?: string | null;
      status: components['schemas']['ProductStatus'];
      /** Is New */
      is_new: boolean;
      /** Published Date */
      published_date?: string | null;
      /**
       * Comments Count
       * @default 0
       */
      comments_count: number | null;
      /** Images */
      images?: components['schemas']['ProductImageRead'][] | null;
      /**
       * Comments
       * @default []
       */
      comments: components['schemas']['CommentRead'][];
    };
    /**
     * ProductStatus
     * @enum {string}
     */
    ProductStatus:
      | 'for_moderation'
      | 'active'
      | 'rejected'
      | 'sold'
      | 'deleted';
    /** RefreshTokenRequest */
    RefreshTokenRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** ResetPasswordConfirm */
    ResetPasswordConfirm: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /**
     * ResetPasswordResponse
     * @example {
     *       "message": " інструкції для скидання паролю надіслані на email"
     *     }
     */
    ResetPasswordResponse: {
      /** Message */
      message: string;
    };
    /** ReviewCreate */
    ReviewCreate: {
      /** Rating */
      rating: number;
      /**
       * Text
       * @default
       */
      text: string | null;
    };
    /** ReviewRead */
    ReviewRead: {
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Rating */
      rating: number;
      /** Text */
      text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      owner: components['schemas']['UserReadSimple'];
      user: components['schemas']['UserReadSimple'];
    };
    /** ReviewUpdate */
    ReviewUpdate: {
      /** Rating */
      rating?: number | null;
      /**
       * Text
       * @default
       */
      text: string | null;
    };
    /** SupportTicketOut */
    SupportTicketOut: {
      /** Id */
      id: number;
      /** User Id */
      user_id: string | null;
      /** User Email */
      user_email: string;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Status */
      status: string;
      assigned_admin: components['schemas']['AssignedAdminOut'] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TokensOutputSchema */
    TokensOutputSchema: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /** Expired In */
      expired_in: number;
    };
    /** UserCreate */
    UserCreate: {
      /** Password */
      password: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Username */
      username?: string | null;
      /**
       * Phone Number
       * @example +380 (67) 123 45 67
       */
      phone_number?: string;
    };
    /** UserLoginSchema */
    UserLoginSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** UserRead */
    UserRead: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Phone Number */
      phone_number: string;
      /** Avatar Url */
      avatar_url?: string | null;
      /** Datetime Create */
      datetime_create?: string | null;
      /** Location */
      location?: string | null;
      /** Description */
      description?: string | null;
      /** Rating */
      rating?: number | null;
      /** Announcements */
      announcements?: {
        [key: string]: unknown;
      }[];
      /**
       * Completed Deals
       * @default 0
       */
      completed_deals: number;
    };
    /** UserReadSimple */
    UserReadSimple: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Superuser */
      is_superuser: boolean;
      /** Username */
      username: string;
      /** Avatar Url */
      avatar_url: string | null;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Password */
      password?: string | null;
      /** Email */
      email?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Is Superuser */
      is_superuser?: boolean | null;
      /** Is Verified */
      is_verified?: boolean | null;
      /** Username */
      username?: string | null;
      /** Phone Number */
      phone_number?: string | null;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /**
     * UserUploadAvatar
     * @example {
     *       "avatar_url": "https://res.cloudinary.comтут далі дані нашої хмари"
     *     }
     */
    UserUploadAvatar: {
      /** Avatar Url */
      avatar_url: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VerifyCodeModel
     * @example {
     *       "message": "Емейл успішно веріфікований"
     *     }
     */
    VerifyCodeModel: {
      /** Message */
      message: string;
    };
    /** VerifyModel */
    VerifyModel: {
      /** Email */
      email: string;
      /** Kod */
      kod: string;
    };
    /** WishlistCreate */
    WishlistCreate: {
      /** Product Id */
      product_id: number;
    };
    /** WishlistResponse */
    WishlistResponse: {
      /** Message */
      message: string;
    };
    /** Body_create_category_categories_post */
    Body_create_category_categories_post: {
      /**
       * Upload File
       * Format: binary
       */
      upload_file: string;
      /** Name */
      name: string;
      /** Parent Category Id */
      parent_category_id?: number;
      /** Image Url */
      image_url?: string;
    };
    /** CategoryUpdate */
    CategoryUpdate: {
      /** Name */
      name?: string | null;
    };
    /** Page[ProductRead] */
    Page_ProductRead_: {
      /** Items */
      items: components['schemas']['ProductRead'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Pages */
      pages: number;
    };
    /** Page[UserRead] */
    Page_UserRead_: {
      /** Items */
      items: components['schemas']['UserRead'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Pages */
      pages: number;
    };
    /** SupportTicketStatusResponse */
    SupportTicketStatusResponse: {
      /** Id */
      id: number;
      /** Status */
      status: string;
      assigned_admin: components['schemas']['AssignedAdminOut'] | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** SupportTicketStatusUpdate */
    SupportTicketStatusUpdate: {
      /**
       * @description Новий статус заявки
       * @example open
       */
      status: components['schemas']['TicketStatus'];
    };
    /**
     * TicketStatus
     * @enum {string}
     */
    TicketStatus: 'open' | 'in_progress' | 'resolved' | 'closed';
    /** UserPartialUpdate */
    UserPartialUpdate: {
      /** Email */
      email?: string | null;
      /** Username */
      username?: string | null;
      /** Phone Number */
      phone_number?: string | null;
      /** Avatar Url */
      avatar_url?: string | null;
      /**
       * Is Active
       * @description Задавати як 0 для false, 1 для true
       */
      is_active?: boolean | null;
    };
    /** Body_create_product_products_post */
    Body_create_product_products_post: {
      /** Files */
      files: string[];
      /** Title */
      title: string;
      /** Description */
      description?: string;
      /** Category Id */
      category_id?: number;
      /** Category */
      category?: string;
      /** Location */
      location?: string;
      /** Is New */
      is_new?: boolean;
      /** Price */
      price: number;
    };
    /** ProductUpdate */
    ProductUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Category Id */
      category_id?: number | null;
      /**
       * Category
       * @description Категорія товару
       */
      category?: string | null;
      /** Location */
      location?: string | null;
      /** Price */
      price?: number | null;
      /** Is New */
      is_new?: boolean | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type SchemaAssignedAdminOut = components['schemas']['AssignedAdminOut'];
export type SchemaBearerResponse = components['schemas']['BearerResponse'];
export type SchemaBodyAuthDbLoginAuthLoginPost =
  components['schemas']['Body_auth_db_login_auth_login_post'];
export type SchemaBodyUploadAvatarUserAvatarPost =
  components['schemas']['Body_upload_avatar_user_avatar_post'];
export type SchemaCategoryRead = components['schemas']['CategoryRead'];
export type SchemaCommentCreate = components['schemas']['CommentCreate'];
export type SchemaCommentRead = components['schemas']['CommentRead'];
export type SchemaCommentUpdate = components['schemas']['CommentUpdate'];
export type SchemaConfirmResetPasswordResponse =
  components['schemas']['ConfirmResetPasswordResponse'];
export type SchemaCreateSupportTicket =
  components['schemas']['CreateSupportTicket'];
export type SchemaErrorModel = components['schemas']['ErrorModel'];
export type SchemaFaqResponse = components['schemas']['FAQResponse'];
export type SchemaHttpValidationError =
  components['schemas']['HTTPValidationError'];
export type SchemaLogoutBody = components['schemas']['LogoutBody'];
export type SchemaNotifications = components['schemas']['Notifications'];
export type SchemaOAuth2AuthorizeResponse =
  components['schemas']['OAuth2AuthorizeResponse'];
export type SchemaPageCommentRead = components['schemas']['Page_CommentRead_'];
export type SchemaProductImageRead = components['schemas']['ProductImageRead'];
export type SchemaProductRead = components['schemas']['ProductRead'];
export type SchemaProductStatus = components['schemas']['ProductStatus'];
export type SchemaRefreshTokenRequest =
  components['schemas']['RefreshTokenRequest'];
export type SchemaResetPasswordConfirm =
  components['schemas']['ResetPasswordConfirm'];
export type SchemaResetPasswordRequest =
  components['schemas']['ResetPasswordRequest'];
export type SchemaResetPasswordResponse =
  components['schemas']['ResetPasswordResponse'];
export type SchemaReviewCreate = components['schemas']['ReviewCreate'];
export type SchemaReviewRead = components['schemas']['ReviewRead'];
export type SchemaReviewUpdate = components['schemas']['ReviewUpdate'];
export type SchemaSupportTicketOut = components['schemas']['SupportTicketOut'];
export type SchemaTokensOutputSchema =
  components['schemas']['TokensOutputSchema'];
export type SchemaUserCreate = components['schemas']['UserCreate'];
export type SchemaUserLoginSchema = components['schemas']['UserLoginSchema'];
export type SchemaUserRead = components['schemas']['UserRead'];
export type SchemaUserReadSimple = components['schemas']['UserReadSimple'];
export type SchemaUserUpdate = components['schemas']['UserUpdate'];
export type SchemaUserUploadAvatar = components['schemas']['UserUploadAvatar'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaVerifyCodeModel = components['schemas']['VerifyCodeModel'];
export type SchemaVerifyModel = components['schemas']['VerifyModel'];
export type SchemaWishlistCreate = components['schemas']['WishlistCreate'];
export type SchemaWishlistResponse = components['schemas']['WishlistResponse'];
export type SchemaBodyCreateCategoryCategoriesPost =
  components['schemas']['Body_create_category_categories_post'];
export type SchemaCategoryUpdate = components['schemas']['CategoryUpdate'];
export type SchemaPageProductRead = components['schemas']['Page_ProductRead_'];
export type SchemaPageUserRead = components['schemas']['Page_UserRead_'];
export type SchemaSupportTicketStatusResponse =
  components['schemas']['SupportTicketStatusResponse'];
export type SchemaSupportTicketStatusUpdate =
  components['schemas']['SupportTicketStatusUpdate'];
export type SchemaTicketStatus = components['schemas']['TicketStatus'];
export type SchemaUserPartialUpdate =
  components['schemas']['UserPartialUpdate'];
export type SchemaBodyCreateProductProductsPost =
  components['schemas']['Body_create_product_products_post'];
export type SchemaProductUpdate = components['schemas']['ProductUpdate'];
export type $defs = Record<string, never>;
export interface operations {
  get_new_users_notifications_notifications__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Notifications'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_by_id_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_products_get: {
    parameters: {
      query?: {
        search?: string | null;
        category_id?: number | null;
        category?: string | null;
        location?: string | null;
        price_from?: number | null;
        price_to?: number | null;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  faq_get_faq_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FAQResponse'][];
        };
      };
    };
  };
  get_comments_by_product_comments_products__product_id__get: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Page size */
        size?: number;
      };
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_CommentRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_comment_comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_comment_comments__comment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_comment_comments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_wishlist_wishlists_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductRead'][];
        };
      };
    };
  };
  add_to_wishlist_wishlists_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WishlistCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WishlistResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_from_wishlist_wishlists_remove__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  auth_db_login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_auth_db_login_auth_login_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTIyMWZmYzktNjQwZi00MzcyLTg2ZDMtY2U2NDJjYmE1NjAzIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTcxNTA0MTkzfQ.M10bjOe45I5Ncu_uXvOmVV8QxnL-nZfcH96U90JaocI",
           *       "token_type": "bearer"
           *     }
           */
          'application/json': components['schemas']['BearerResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  auth_db_logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_auth_user_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserLoginSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensOutputSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_auth_user_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensOutputSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  forgot_password_auth_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResetPasswordResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reset_users_password_auth_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordConfirm'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfirmResetPasswordResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  users_current_user_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  users_patch_current_user_users_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorModel'];
        };
      };
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  users_user_users__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not a superuser. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The user does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  users_delete_user_users__id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not a superuser. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The user does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  users_patch_user_users__id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorModel'];
        };
      };
      /** @description Missing token or inactive user. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not a superuser. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The user does not exist. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  oauth_google_db_authorize_auth_google_authorize_get: {
    parameters: {
      query?: {
        scopes?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OAuth2AuthorizeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  oauth_google_db_callback_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        code_verifier?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_reviews_users__user_id__reviews_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_review_users__user_id__reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_review_users__user_id__reviews_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_review_users__user_id__reviews_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_rating_users__user_id__rating_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_all_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryRead'][];
        };
      };
    };
  };
  get_one_categories__category_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  verify_code_auth_verify_code_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyModel'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerifyCodeModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  send_support_message_support_tickets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSupportTicket'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportTicketOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_avatar_user_avatar_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_avatar_user_avatar_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserUploadAvatar'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_avatar_user_avatar_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Проблема видаленням на стороні клоудінарі,ось яка помилка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Юзер не має ще\вже аватарки */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Невалідне юрл посилання на зображення */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_me_user_profile_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Інформація про користувача успішно отримана */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Користувач не автентифікований */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_user_users__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_user_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserPartialUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_users_get: {
    parameters: {
      query?: {
        search?: string | null;
        is_superuser?: boolean | null;
        is_active?: boolean | null;
        is_verified?: boolean | null;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_UserRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_support_tickets_tickets__get: {
    parameters: {
      query?: {
        /** @description Фільтр за статусом заявки */
        status?: components['schemas']['TicketStatus'] | null;
        /** @description Номер сторінки */
        page?: number;
        /** @description Кількість заявок на сторінку */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_ticket_status_tickets__ticket_id__status_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SupportTicketStatusUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportTicketStatusResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_ticket_details_tickets__ticket_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportTicketOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_ticket_tickets_ticket_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  approve_product_products__product_id__approve_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_product_products__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_products_get: {
    parameters: {
      query?: {
        search?: string | null;
        status?: components['schemas']['ProductStatus'] | null;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ProductRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_category_categories__category_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_category_categories__category_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_category_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_category_categories_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_products_get: {
    parameters: {
      query?: {
        search?: string | null;
        category_id?: number | null;
        category?: string | null;
        location?: string | null;
        price_from?: number | null;
        price_to?: number | null;
        status?: components['schemas']['ProductStatus'] | null;
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ProductRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_product_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_product_products_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_by_id_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_product_products__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_product_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  authenticated_route_authenticated_route_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  button_button_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
